---
title: "Iteration and list columns"
author: "Wenzhao Wu"
date: "11/9/2020"
output: github_document
---

```{r setup}
library(tidyverse)
set.seed(1)

knitr::opts_chunk$set(
  fig.width = 12,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Lists

You can put everything in a list.

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, nrow = 2, ncol = 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l
```

## `for` loop

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(40, 0, 5),
    c = rnorm(30, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) < 3) {
    stop("Input must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply that function to each list element

```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a for loop.

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```

## Let's try map!

```{r}
map(list_norms, mean_and_sd)
```

What if I want a different function?

```{r}
map(list_norms, median)
map(list_norms, IQR)
```

```{r}
output = map_dbl(list_norms, median, .id = "input")
```

```{r}
output = map_dfr(list_norms, mean_and_sd, .id = "input")
```

## List columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df %>% pull(name)
listcol_df %>% pull(samp)

listcol_df %>%
  filter(name == "a")
mean_and_sd(listcol_df$samp[[1]])
```

```{r}
map(listcol_df$samp, mean_and_sd)
```

Add a new column

```{r}
listcol_df = 
  listcol_df %>% 
  mutate(summary = map(samp, mean_and_sd),
         medians = map_dbl(samp, median))

listcol_df
```

