---
title: "Writing Functions"
author: "Wenzhao Wu"
date: "11/9/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 12,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-scores

```{r}
z_scores = function(x) {
        
  if (!is.numeric(x)) {
     stop("Argument x should be numeric")      
  }        
  
  if (length(x) < 3) {
     stop("Input must have at least 3 numbers")
  }     
  z = (x - mean(x)) / sd(x)
  
  return(z)
              
}

z_scores(x_vec)
```

Try my function on some other things. These should give errors.

```{r, error = TRUE}
z_scores(3)
z_scores("my name is jeff")
z_scores(iris)
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```

## Multiple outputs

```{r}
mean_and_sd = function(x) {
        
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")      
  }        
  
  if (length(x) < 3) {
    stop("Input must have at least 3 numbers")
  }   
        
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
              
}

```

Check that the function works.

```{r}
x_vec = rnorm(100, mean = 0, sd = 1)
mean_and_sd(x_vec)
```

## Multiple inputs

```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 3, sd = 2)
  )

sim_data %>%
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

```{r}
sim_mean_sd = function(samp_size, mu, sigma) {
        
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma)
    )

  sim_data %>%
    summarize(
      mean = mean(x),
      sd = sd(x)
    )      
}

sim_mean_sd(100, 6, 3)
```

